// Root API router: mounts all sub-routers and a health endpoint.
import { Router } from "express";
import { authRouter } from "./auth.routes";
import { leadsRouter } from "./leads.routes";
import { pitchesRouter } from "./pitches.routes";
import { templatesRouter } from "./templates.routes";
import { eventsRouter } from "./events.routes";
import { customFieldsRouter, dealStagesRouter } from "./custom-fields.routes";
import { sequencesRouter } from "./sequences.routes";
import { aiRouter } from "./ai.routes";
import { statsRouter } from "./stats.routes";
import { settingsRouter } from "./settings.routes";
import { revenueRouter } from "./revenue.routes";
import { routingRouter } from "./routing.routes";
import { calendarRouter } from "./calendar.routes";
import { documentsRouter } from "./documents.routes";
import { apiKeysRouter } from "./api-keys.routes";
import { monitoringRouter } from "./monitoring.routes";
import { optimizationRouter } from "./optimization.routes";
import { usersRouter } from "./users.routes";
import { inboundRouter } from "./inbound.routes";
import { publicBookingRouter } from "./public-booking.routes";
import { integrationsRouter } from "./integrations.routes";
import { activationRouter } from "./activation.routes";
import { complianceRouter } from "./compliance.routes";
import { publicUnsubscribeRouter } from "./public-unsubscribe.routes";
import { relationshipsRouter } from "./relationships.routes";
import { googleRouter } from "./google.routes";
import { conversationsRouter } from "./conversations.routes";
import { playbooksRouter } from "./playbooks.routes";
import { qualificationRouter } from "./qualification.routes";
import { queuesRouter } from "./queues.routes";
import { attributionRouter } from "./attribution.routes";
import { outboundWebhooksRouter } from "./outbound-webhooks.routes";
import { signalsRouter } from "./signals.routes";
import { agentsRouter } from "./agents.routes";
import { marketplaceRouter } from "./marketplace.routes";
import { rankingsRouter } from "./rankings.routes";
import { graphRouter } from "./graph.routes";
import { evidenceRouter } from "./evidence.routes";
import { automationAuditRouter } from "./automation-audit.routes";
import { workspaceThresholdsRouter } from "./workspace-thresholds.routes";

export const apiRouter = Router();

apiRouter.get("/health", (_req, res) => {
  res.json({
    status: "ok",
    time: new Date().toISOString(),
  });
});

apiRouter.use("/auth", authRouter);
apiRouter.use("/public/booking", publicBookingRouter);
apiRouter.use("/public/unsubscribe", publicUnsubscribeRouter);
apiRouter.use("/integrations", integrationsRouter);
apiRouter.use("/activation", activationRouter);
apiRouter.use("/compliance", complianceRouter);
apiRouter.use("/relationships", relationshipsRouter);
apiRouter.use("/google", googleRouter);
apiRouter.use("/conversations", conversationsRouter);
apiRouter.use("/leads", leadsRouter);
apiRouter.use("/pitches", pitchesRouter);
apiRouter.use("/templates", templatesRouter);
apiRouter.use("/events", eventsRouter);
apiRouter.use("/custom-fields", customFieldsRouter);
apiRouter.use("/custom-fields/stages", dealStagesRouter);
apiRouter.use("/sequences", sequencesRouter);
apiRouter.use("/stats", statsRouter);
apiRouter.use("/ai", aiRouter);
apiRouter.use("/settings", settingsRouter);
apiRouter.use("/revenue", revenueRouter);
apiRouter.use("/routing", routingRouter);
apiRouter.use("/calendar", calendarRouter);
apiRouter.use("/documents", documentsRouter);
apiRouter.use("/api-keys", apiKeysRouter);
apiRouter.use("/monitoring", monitoringRouter);
apiRouter.use("/optimization", optimizationRouter);
apiRouter.use("/admin/users", usersRouter);
apiRouter.use("/inbound", inboundRouter);
apiRouter.use("/playbooks", playbooksRouter);
apiRouter.use("/qualification", qualificationRouter);
apiRouter.use("/queues", queuesRouter);
apiRouter.use("/attribution", attributionRouter);
apiRouter.use("/webhooks", outboundWebhooksRouter);
apiRouter.use("/signals", signalsRouter);
apiRouter.use("/agents", agentsRouter);
apiRouter.use("/marketplace", marketplaceRouter);
apiRouter.use("/rankings", rankingsRouter);
apiRouter.use("/graph", graphRouter);
apiRouter.use("/evidence", evidenceRouter);
apiRouter.use("/automation-audit", automationAuditRouter);
apiRouter.use("/workspace-thresholds", workspaceThresholdsRouter);
