import React, { useEffect, useState } from 'react';
import { AlertTriangle, CheckCircle2, ExternalLink, Loader2, Plus, Save, ShieldCheck, Trash2 } from 'lucide-react';
import { ApiError } from '../services/apiClient';
import { DeliverabilityStatus, SuppressionEntry, addSuppression, deleteSuppression, fetchComplianceStatus, fetchSuppressions, saveCompliancePolicy, savePublicBookingUrl } from '../services/activationService';

export const ComplianceCenter: React.FC = () => {
  const [status, setStatus] = useState<DeliverabilityStatus | null>(null);
  const [items, setItems] = useState<SuppressionEntry[]>([]);
  const [email, setEmail] = useState(''); const [reason, setReason] = useState('Do not contact');
  const [publicUrl, setPublicUrl] = useState('');
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = () => Promise.all([fetchComplianceStatus(), fetchSuppressions()]).then(([nextStatus, nextItems]) => { setStatus(nextStatus); setPublicUrl(nextStatus.publicBooking.url); setItems(nextItems); }).catch((err) => setError(err instanceof ApiError ? err.message : 'Compliance data could not be loaded.'));
  useEffect(() => { load(); }, []);
  if (!status) return <section className="rounded-2xl border border-slate-800 p-6"><span className="flex items-center gap-2 text-xs text-slate-400"><Loader2 className="h-4 w-4 animate-spin" />Loading compliance center…</span>{error && <p role="alert" className="mt-2 text-xs text-rose-400">{error}</p>}</section>;
  const updatePolicy = async () => { setBusy(true); setError(null); try { setStatus(await saveCompliancePolicy({ dailySendLimit: status.dailySendLimit, bounceThresholdPercent: status.bounceThresholdPercent, complaintThresholdPercent: status.complaintThresholdPercent })); } catch (err) { setError(err instanceof ApiError ? err.message : 'Policy could not be saved.'); } finally { setBusy(false); } };
  const updatePublicUrl = async () => { setBusy(true); setError(null); try { const next = await savePublicBookingUrl(publicUrl); setStatus(next); setPublicUrl(next.publicBooking.url); } catch (err) { setError(err instanceof ApiError ? err.message : 'Public booking URL could not be saved.'); } finally { setBusy(false); } };
  const add = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(null); try { const entry = await addSuppression(email, reason); setItems((current) => [entry, ...current.filter((item) => item.email !== entry.email)]); setEmail(''); } catch (err) { setError(err instanceof ApiError ? err.message : 'Recipient could not be suppressed.'); } finally { setBusy(false); } };
  return <section aria-labelledby="compliance-title" className="space-y-5 rounded-2xl border border-slate-800 bg-slate-950/40 p-6">
    <div><h3 id="compliance-title" className="flex items-center gap-2 text-sm font-bold text-white"><ShieldCheck className="h-4 w-4 text-emerald-400" />Deliverability & compliance</h3><p className="mt-1 text-[11px] text-slate-500">Sending pauses automatically when verification, volume, bounce, or complaint safety checks fail.</p></div>
    <div className={`rounded-xl border p-4 text-xs ${status.paused ? 'border-rose-500/30 bg-rose-500/10 text-rose-300' : 'border-emerald-500/30 bg-emerald-500/10 text-emerald-300'}`}>{status.paused ? <><AlertTriangle className="mr-2 inline h-4 w-4" />Sending paused: {status.reasons.join(' ')}</> : <><CheckCircle2 className="mr-2 inline h-4 w-4" />Sender checks are passing.</>}</div>
    <div className="grid gap-3 sm:grid-cols-3"><label className="text-[10px] font-bold uppercase text-slate-400">Daily limit<input type="number" min="1" max="10000" value={status.dailySendLimit} onChange={(e) => setStatus({ ...status, dailySendLimit: Number(e.target.value) })} className="mt-2 w-full rounded-lg border border-slate-800 bg-slate-900 p-2 text-sm text-white" /></label><label className="text-[10px] font-bold uppercase text-slate-400">Bounce pause %<input type="number" min="0.1" step="0.1" value={status.bounceThresholdPercent} onChange={(e) => setStatus({ ...status, bounceThresholdPercent: Number(e.target.value) })} className="mt-2 w-full rounded-lg border border-slate-800 bg-slate-900 p-2 text-sm text-white" /></label><label className="text-[10px] font-bold uppercase text-slate-400">Complaint pause %<input type="number" min="0.01" step="0.01" value={status.complaintThresholdPercent} onChange={(e) => setStatus({ ...status, complaintThresholdPercent: Number(e.target.value) })} className="mt-2 w-full rounded-lg border border-slate-800 bg-slate-900 p-2 text-sm text-white" /></label></div>
    <button type="button" disabled={busy} onClick={updatePolicy} className="rounded-lg bg-sky-600 px-4 py-2 text-xs font-bold text-white disabled:opacity-50">Save safety policy</button>
    <div className="space-y-3"><h4 className="text-xs font-bold text-white">Public booking domain</h4><div className="rounded-xl border border-slate-800 bg-slate-900/50 p-4"><div className="grid gap-3 sm:grid-cols-[1fr_auto]"><label className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Public booking URL<input type="url" value={publicUrl} onChange={(e) => setPublicUrl(e.target.value)} placeholder="https://book.example.com" className="mt-2 w-full rounded-lg border border-slate-800 bg-slate-950 p-2.5 text-sm normal-case tracking-normal text-white" /></label><button type="button" disabled={busy || !publicUrl} onClick={updatePublicUrl} className="self-end inline-flex items-center justify-center gap-2 rounded-lg bg-sky-600 px-4 py-2.5 text-xs font-bold text-white disabled:opacity-50"><Save className="h-4 w-4" />Save URL</button></div><div className="mt-3 grid gap-2 text-[11px] text-slate-400 sm:grid-cols-2"><p>Sending domain: <strong className="text-slate-200">{status.sender.domain || 'not configured'}</strong></p><p>Booking domain: <strong className="text-slate-200">{status.publicBooking.domain || 'not configured'}</strong></p></div>{status.publicBooking.isLocal ? <p className="mt-3 rounded-lg border border-sky-500/20 bg-sky-500/10 p-3 text-[11px] leading-relaxed text-sky-200">Local development is working normally. localhost cannot match an email domain and this does not pause sending. Before production, point a public HTTPS hostname such as <strong>book.{status.sender.domain || 'example.com'}</strong> to this LeadScout server, then save that URL here.</p> : !status.publicBooking.domainsAligned ? <p className="mt-3 rounded-lg border border-amber-500/20 bg-amber-500/10 p-3 text-[11px] leading-relaxed text-amber-200">The generated link domain differs from the sending domain. Use your company domain or a subdomain such as <strong>book.{status.sender.domain || 'example.com'}</strong>. DNS and HTTPS must route it to this application; saving the URL here does not create DNS automatically.</p> : <p className="mt-3 flex items-center gap-2 text-[11px] text-emerald-300"><CheckCircle2 className="h-4 w-4" />Booking and sending domains are aligned.</p>}<a href={status.publicBooking.url} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1 text-[11px] font-bold text-sky-400">Open configured address <ExternalLink className="h-3 w-3" /></a></div></div>
    <div><h4 className="mb-2 text-xs font-bold text-white">Domain health guidance</h4><ul className="grid gap-2 sm:grid-cols-2">{status.guidance.map((item) => <li key={item.id} className="flex items-center gap-2 text-xs text-slate-400">{item.ok ? <CheckCircle2 className="h-4 w-4 text-emerald-400" /> : <AlertTriangle className="h-4 w-4 text-amber-400" />}{item.label}</li>)}</ul></div>
    <div><h4 className="text-xs font-bold text-white">Suppression list ({items.length})</h4><form onSubmit={add} className="mt-3 grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="recipient@example.com" aria-label="Recipient email" className="rounded-lg border border-slate-800 bg-slate-900 p-2 text-xs text-white" /><input required minLength={2} value={reason} onChange={(e) => setReason(e.target.value)} placeholder="Reason" aria-label="Suppression reason" className="rounded-lg border border-slate-800 bg-slate-900 p-2 text-xs text-white" /><button disabled={busy} className="flex items-center justify-center gap-1 rounded-lg border border-slate-700 px-3 py-2 text-xs font-bold text-slate-200"><Plus className="h-3 w-3" />Suppress</button></form>{items.length === 0 ? <p className="mt-3 rounded-lg border border-dashed border-slate-800 p-4 text-center text-xs text-slate-500">No suppressed recipients.</p> : <ul className="mt-3 max-h-56 space-y-2 overflow-auto">{items.map((item) => <li key={item.id} className="flex items-center justify-between rounded-lg bg-slate-900/60 p-3"><span className="min-w-0"><span className="block truncate text-xs text-slate-200">{item.email}</span><span className="block text-[10px] text-slate-500">{item.source} · {item.reason}</span></span><button type="button" aria-label={`Remove ${item.email} from suppression list`} onClick={async () => { await deleteSuppression(item.email); setItems((current) => current.filter((candidate) => candidate.id !== item.id)); }} className="p-2 text-slate-500 hover:text-rose-400"><Trash2 className="h-4 w-4" /></button></li>)}</ul>}</div>
    {error && <p role="alert" className="text-xs text-rose-400">{error}</p>}
  </section>;
};
